#!/bin/sh

### BEGIN INIT INFO
# Provides:          PikonekMain
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the pikonek main app
# Description:       No Description
### END INIT INFO

DIR=/etc/pikonek
DAEMON=$DIR/main.py
DAEMON_NAME=pikonekmain
DAEMON_OPTS=""

set -e
# Root is needed to use the GPIO pins on the Raspberry
# DAEMON_USER=root

PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    touch /var/log/pikonek.log
    chown pikonek:pikonek /var/log/pikonek.log
    chmod 0644 /var/log/pikonek.log
    chown pikonek:pikonek /etc/pikonek/database/db.wifirouter
    export PYARMOR_LICENSE=/etc/pikonek/license/license.lic
    # activate venv
    # source "$DIR/venv/bin/activate" &> /dev/null
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    # deactivate venv
    # deactivate &> /dev/null
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
